# Generated by Django 4.2.3 on 2023-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish"]},
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_c4286e_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-publish"], name="blog_post_publish_bb7600_idx"
            ),
        ),
    ]
